@baseUrl =  http://localhost:3000/api
@botId = 

### ---------------------------------------------
### create
### ---------------------------------------------
### 1
POST {{baseUrl}}/bot

{
  "name": "Test",
  "notificationTo": "https://example.com/"
}


### ---------------------------------------------
### Read
### ---------------------------------------------
GET {{baseUrl}}/bot/{{botId}}


### ---------------------------------------------
### Update
### ---------------------------------------------

PUT {{baseUrl}}/bot/{{botId}}

{
  "name": "Test-updated",
  "notificationTo": "https://example.com/"
}


### ---------------------------------------------
### Delete
### ---------------------------------------------

DELETE {{baseUrl}}/bot/{{botId}}


### ---------------------------------------------
### WebHook
### ---------------------------------------------
POST  {{baseUrl}}/webhook/{{botId}}
X-Gitlab-Token: 
